 Container qdrantdb  Running
 Container mysqldb  Running
 Container api  Created
Attaching to api
api  | INFO:     Started server process [1]
api  | INFO:     Waiting for application startup.
api  | INFO:     Application startup complete.
api  | INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
api  | Error connecting to MySQL: 2003 (HY000): Can't connect to MySQL server on 'localhost:3306' (99)
api  | INFO:     192.168.65.1:23713 - "GET /docs HTTP/1.1" 200 OK
api  | INFO:     192.168.65.1:23713 - "GET /openapi.json HTTP/1.1" 200 OK
api  | INFO:     192.168.65.1:23714 - "POST /detibot/insert_source HTTP/1.1" 500 Internal Server Error
api  | ERROR:    Exception in ASGI application
api  | Traceback (most recent call last):
api  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 411, in run_asgi
api  |     result = await app(  # type: ignore[func-returns-value]
api  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
api  |     return await self.app(scope, receive, send)
api  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api  |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
api  |     await super().__call__(scope, receive, send)
api  |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
api  |     await self.middleware_stack(scope, receive, send)
api  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
api  |     raise exc
api  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
api  |     await self.app(scope, receive, _send)
api  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 93, in __call__
api  |     await self.simple_response(scope, receive, send, request_headers=headers)
api  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 148, in simple_response
api  |     await self.app(scope, receive, send)
api  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
api  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
api  |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
api  |     raise exc
api  |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
api  |     await app(scope, receive, sender)
api  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
api  |     await self.middleware_stack(scope, receive, send)
api  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
api  |     await route.handle(scope, receive, send)
api  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
api  |     await self.app(scope, receive, send)
api  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
api  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
api  |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
api  |     raise exc
api  |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
api  |     await app(scope, receive, sender)
api  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
api  |     response = await func(request)
api  |                ^^^^^^^^^^^^^^^^^^^
api  |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
api  |     raw_response = await run_endpoint_function(
api  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api  |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
api  |     return await dependant.call(**values)
api  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api  |   File "/usr/src/app/controller.py", line 33, in KnowledgeSource
api  |     db.insert_source(source)
api  |   File "/usr/src/app/Services/storing.py", line 53, in insert_source
api  |     self.cursor.execute(insert_sql, (source.url,source.loader_type,source.description,Id)) # maybe put here a logger and a try/ctach
api  |     ^^^^^^^^^^^
api  | AttributeError: 'H2' object has no attribute 'cursor'
Gracefully stopping... (press Ctrl+C again to force)
Aborting on container exit...
canceled
